# Generated by Django 3.0.2 on 2020-01-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('avaliacao', '0001_initial'),
        ('core', '0002_pontosturisticos_atracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='avaliacao',
            field=models.ManyToManyField(to='avaliacao.Avaliacao'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.Comentarios'),
        ),
    ]
