# Generated by Django 3.0.2 on 2020-01-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0001_initial'),
        ('core', '0003_auto_20200113_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='localizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localizacao.Localizacao'),
            preserve_default=False,
        ),
    ]
